---
# Playbook para verificar el estado de los recursos desplegados

- name: Check Azure Infrastructure Status
  hosts: localhost
  gather_facts: true
  collections:
    - azure.azcollection
  
  tasks:
    - name: Get Resource Group information
      azure_rm_resourcegroup_info:
        name: "{{ resource_group_name }}"
      register: rg_info

    - name: Display Resource Group status
      debug:
        msg:
          - "Resource Group: {{ rg_info.resourcegroups[0].name if rg_info.resourcegroups else 'Not found' }}"
          - "Location: {{ rg_info.resourcegroups[0].location if rg_info.resourcegroups else 'N/A' }}"
          - "Provisioning State: {{ rg_info.resourcegroups[0].properties.provisioningState if rg_info.resourcegroups else 'N/A' }}"
      when: rg_info.resourcegroups | length > 0

    - name: Get Virtual Network information
      azure_rm_virtualnetwork_info:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vnet_name }}"
      register: vnet_info
      when: rg_info.resourcegroups | length > 0

    - name: Display VNet status
      debug:
        msg:
          - "Virtual Network: {{ vnet_info.virtualnetworks[0].name if vnet_info.virtualnetworks else 'Not found' }}"
          - "Address Space: {{ vnet_info.virtualnetworks[0].address_prefixes if vnet_info.virtualnetworks else 'N/A' }}"
      when: rg_info.resourcegroups | length > 0 and vnet_info.virtualnetworks is defined

    - name: Get MySQL Server information
      azure_rm_resource_info:
        resource_group: "{{ resource_group_name }}"
        provider: DBforMySQL
        resource_type: flexibleServers
        resource_name: "{{ mysql_server_name }}"
        api_version: "2021-12-01-preview"
      register: mysql_info
      ignore_errors: true
      when: rg_info.resourcegroups | length > 0

    - name: Display MySQL Server status
      debug:
        msg:
          - "MySQL Server: {{ mysql_info.response[0].name if mysql_info.response else 'Not found' }}"
          - "State: {{ mysql_info.response[0].properties.state if mysql_info.response else 'N/A' }}"
          - "FQDN: {{ mysql_info.response[0].properties.fullyQualifiedDomainName if mysql_info.response else 'N/A' }}"
          - "Version: {{ mysql_info.response[0].properties.version if mysql_info.response else 'N/A' }}"
      when: rg_info.resourcegroups | length > 0 and mysql_info.response is defined

    - name: Get Backend Web App information
      azure_rm_webapp_info:
        resource_group: "{{ resource_group_name }}"
        name: "{{ backend_app_name }}"
      register: backend_info
      ignore_errors: true
      when: rg_info.resourcegroups | length > 0

    - name: Display Backend App status
      debug:
        msg:
          - "Backend App: {{ backend_info.webapps[0].name if backend_info.webapps else 'Not found' }}"
          - "State: {{ backend_info.webapps[0].state if backend_info.webapps else 'N/A' }}"
          - "URL: https://{{ backend_info.webapps[0].default_host_name if backend_info.webapps else 'N/A' }}"
      when: rg_info.resourcegroups | length > 0 and backend_info.webapps is defined

    - name: Get Frontend Web App information
      azure_rm_webapp_info:
        resource_group: "{{ resource_group_name }}"
        name: "{{ frontend_app_name }}"
      register: frontend_info
      ignore_errors: true
      when: rg_info.resourcegroups | length > 0

    - name: Display Frontend App status
      debug:
        msg:
          - "Frontend App: {{ frontend_info.webapps[0].name if frontend_info.webapps else 'Not found' }}"
          - "State: {{ frontend_info.webapps[0].state if frontend_info.webapps else 'N/A' }}"
          - "URL: https://{{ frontend_info.webapps[0].default_host_name if frontend_info.webapps else 'N/A' }}"
      when: rg_info.resourcegroups | length > 0 and frontend_info.webapps is defined

    - name: Summary
      debug:
        msg:
          - "=========================================="
          - "   Infrastructure Status Summary"
          - "=========================================="
          - ""
          - "Resource Group: {{ 'EXISTS' if rg_info.resourcegroups | length > 0 else 'NOT FOUND' }}"
          - "Virtual Network: {{ 'EXISTS' if (vnet_info.virtualnetworks is defined and vnet_info.virtualnetworks | length > 0) else 'NOT FOUND' }}"
          - "MySQL Server: {{ 'EXISTS (' + mysql_info.response[0].properties.state + ')' if (mysql_info.response is defined and mysql_info.response | length > 0) else 'NOT FOUND' }}"
          - "Backend App: {{ 'EXISTS (' + backend_info.webapps[0].state + ')' if (backend_info.webapps is defined and backend_info.webapps | length > 0) else 'NOT FOUND' }}"
          - "Frontend App: {{ 'EXISTS (' + frontend_info.webapps[0].state + ')' if (frontend_info.webapps is defined and frontend_info.webapps | length > 0) else 'NOT FOUND' }}"
          - ""
          - "=========================================="
