---
# Playbook para desplegar MySQL Flexible Server
# Configuración mínima para capa gratuita

- name: Deploy MySQL Flexible Server to Azure
  hosts: localhost
  gather_facts: true
  collections:
    - azure.azcollection
  
  tasks:
    - name: Display MySQL deployment information
      debug:
        msg:
          - "Deploying MySQL Flexible Server"
          - "Server Name: {{ mysql_server_name }}"
          - "SKU: {{ mysql_sku_name }}"
          - "Storage: {{ mysql_storage_size_gb }} GB"

    - name: Check if Resource Group exists
      azure_rm_resourcegroup_info:
        name: "{{ resource_group_name }}"
      register: rg_info

    - name: Fail if Resource Group doesn't exist
      fail:
        msg: "Resource Group {{ resource_group_name }} does not exist. Run deploy-infrastructure.yml first."
      when: rg_info.resourcegroups | length == 0

    - name: Get Subnet information
      azure_rm_subnet_info:
        resource_group: "{{ resource_group_name }}"
        virtual_network_name: "{{ vnet_name }}"
        name: "{{ subnet_name }}"
      register: subnet_info

    - name: Create MySQL Flexible Server
      azure_rm_resource:
        resource_group: "{{ resource_group_name }}"
        provider: DBforMySQL
        resource_type: flexibleServers
        resource_name: "{{ mysql_server_name }}"
        api_version: "2021-12-01-preview"
        body:
          location: "{{ location }}"
          tags: "{{ common_tags }}"
          sku:
            name: "{{ mysql_sku_name }}"
            tier: "Burstable"
          properties:
            administratorLogin: "{{ mysql_admin_username }}"
            administratorLoginPassword: "{{ mysql_admin_password }}"
            version: "{{ mysql_version }}"
            storage:
              storageSizeGB: "{{ mysql_storage_size_gb }}"
              autoGrow: "Enabled"
            backup:
              backupRetentionDays: "{{ mysql_backup_retention_days }}"
              geoRedundantBackup: "Disabled"
            highAvailability:
              mode: "Disabled"
            network:
              delegatedSubnetResourceId: "{{ subnet_info.subnets[0].id }}"
              privateDnsZoneResourceId: null
        state: present
      register: mysql_server
      async: 3600  # 60 minutos timeout (la creación puede tomar tiempo)
      poll: 30

    - name: Wait for MySQL Server to be ready
      debug:
        msg: "MySQL Server is being created. This may take 10-15 minutes. Check Azure Portal for status."
      when: mysql_server is changed

    - name: Create MySQL Database
      azure_rm_resource:
        resource_group: "{{ resource_group_name }}"
        provider: DBforMySQL
        resource_type: flexibleServers
        resource_name: "{{ mysql_server_name }}"
        subresource:
          - type: databases
            name: "{{ mysql_database_name }}"
        api_version: "2021-12-01-preview"
        body:
          properties:
            charset: "utf8mb4"
            collation: "utf8mb4_unicode_ci"
        state: present

    - name: Configure firewall rule to allow Azure services
      azure_rm_resource:
        resource_group: "{{ resource_group_name }}"
        provider: DBforMySQL
        resource_type: flexibleServers
        resource_name: "{{ mysql_server_name }}"
        subresource:
          - type: firewallRules
            name: "AllowAllAzureServicesAndResourcesWithinAzureIps"
        api_version: "2021-12-01-preview"
        body:
          properties:
            startIpAddress: "0.0.0.0"
            endIpAddress: "0.0.0.0"
        state: present

    - name: Configure firewall rule to allow all IPs (for development)
      azure_rm_resource:
        resource_group: "{{ resource_group_name }}"
        provider: DBforMySQL
        resource_type: flexibleServers
        resource_name: "{{ mysql_server_name }}"
        subresource:
          - type: firewallRules
            name: "AllowAll"
        api_version: "2021-12-01-preview"
        body:
          properties:
            startIpAddress: "0.0.0.0"
            endIpAddress: "255.255.255.255"
        state: present
      when: env_name == "development" or env_name == "production"

    - name: Display MySQL Server information
      debug:
        msg:
          - "MySQL Flexible Server deployed successfully!"
          - "Server Name: {{ mysql_server_name }}"
          - "FQDN: {{ mysql_server_name }}.mysql.database.azure.com"
          - "Admin Username: {{ mysql_admin_username }}"
          - "Database: {{ mysql_database_name }}"
          - "Connection String: mysql://{{ mysql_admin_username }}:PASSWORD@{{ mysql_server_name }}.mysql.database.azure.com:3306/{{ mysql_database_name }}"
