---
# Playbook principal para desplegar infraestructura en Azure
# Recursos configurados para capa gratuita

- name: Deploy Infrastructure to Azure
  hosts: localhost
  gather_facts: true
  collections:
    - azure.azcollection
  
  tasks:
    - name: Display deployment information
      debug:
        msg:
          - "Deploying {{ project_name }} to Azure"
          - "Environment: {{ env_name }}"
          - "Location: {{ location }}"
          - "Resource Group: {{ resource_group_name }}"

    - name: Create Resource Group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ location }}"
        tags: "{{ common_tags }}"
      register: rg_output

    - name: Display Resource Group info
      debug:
        msg: "Resource Group '{{ rg_output.state.name }}' created/updated"

    - name: Create Virtual Network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vnet_name }}"
        address_prefixes_cidr:
          - "{{ vnet_cidr }}"
        tags: "{{ common_tags }}"
      register: vnet_output

    - name: Create Subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group_name }}"
        virtual_network_name: "{{ vnet_name }}"
        name: "{{ subnet_name }}"
        address_prefix_cidr: "{{ subnet_cidr }}"
        delegations:
          - name: "mysql-delegation"
            serviceName: "Microsoft.DBforMySQL/flexibleServers"
      register: subnet_output

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ nsg_name }}"
        tags: "{{ common_tags }}"
        rules:
          - name: "Allow-HTTP"
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 100
            direction: Inbound
          - name: "Allow-HTTPS"
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 110
            direction: Inbound
          - name: "Allow-Backend"
            protocol: Tcp
            destination_port_range: 5000
            access: Allow
            priority: 120
            direction: Inbound
          - name: "Allow-MySQL"
            protocol: Tcp
            destination_port_range: 3306
            access: Allow
            priority: 130
            direction: Inbound
            source_address_prefix: "{{ vnet_cidr }}"

    - name: Display networking info
      debug:
        msg:
          - "Virtual Network: {{ vnet_output.state.name }}"
          - "Subnet: {{ subnet_output.state.name }}"
          - "Network Security Group created"
