---
# Variables globales para el despliegue en Azure
# Capa gratuita / Recursos mínimos

# Información básica del proyecto
project_name: "autoscaling-system"
env_name: "production"
location: "eastus"  # Región de Azure (East US tiene buena disponibilidad de capa gratuita)
azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"

# Resource Group
resource_group_name: "rg-{{ project_name }}-{{ env_name }}"

# Networking
vnet_name: "vnet-{{ project_name }}"
vnet_cidr: "10.0.0.0/16"
subnet_name: "subnet-{{ project_name }}"
subnet_cidr: "10.0.1.0/24"
nsg_name: "nsg-{{ project_name }}"

# MySQL Flexible Server (Configuración MÍNIMA - Usa créditos gratuitos)
mysql_server_name: "mysql-{{ project_name }}-{{ env_name | lower }}"
mysql_admin_username: "sqladmin"
mysql_admin_password: "{{ lookup('env', 'MYSQL_PASSWORD') | default('ChangeThisPassword123!', true) }}"
mysql_database_name: "autoscaling_db"
mysql_sku_name: "Standard_B1s"  # Burstable, 1 vCore, 1 GB RAM (EL MÁS PEQUEÑO POSIBLE)
mysql_storage_size_gb: 20  # Mínimo permitido
mysql_backup_retention_days: 7
mysql_version: "8.0.21"

# Container Registry (opcional, puede usar Docker Hub)
use_acr: false
acr_name: "acr{{ project_name }}{{ env_name }}"
acr_sku: "Basic"

# Azure Container Apps (Consumo - Free Tier)
log_analytics_workspace_name: "law-{{ project_name }}-{{ env_name }}"
container_apps_environment_name: "cae-{{ project_name }}-{{ env_name }}"
backend_container_app_name: "aca-{{ project_name }}-backend-{{ env_name }}"
frontend_container_app_name: "aca-{{ project_name }}-frontend-{{ env_name }}"

backend_docker_image: "christianpe1/autoscaling-backend:latest"  # Cambia por tu imagen
frontend_docker_image: "christianpe1/autoscaling-frontend:latest"  # Cambia por tu imagen

# Container App resources (mantener dentro del nivel gratuito)
backend_container_cpu: 0.25
backend_container_memory: "0.5Gi"
frontend_container_cpu: 0.25
frontend_container_memory: "0.5Gi"
backend_min_replicas: 1
backend_max_replicas: 2
frontend_min_replicas: 1
frontend_max_replicas: 2

# Tags comunes
common_tags:
  Environment: "{{ env_name }}"
  Project: "{{ project_name }}"
  ManagedBy: "Ansible"
  CostCenter: "Free-Tier"

# Configuración de seguridad
allowed_ip_addresses:
  - "0.0.0.0/0"  # Permite todo (ajusta según necesites)
