name: Deploy to AWS with Pulumi

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
      
      - name: Install Python dependencies
        run: |
          cd infrastructure
          pip install -r requirements.txt
      
      - name: Pulumi Preview
        if: github.event_name == 'pull_request'
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: production
          work-dir: infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      
      - name: Pulumi Up
        if: github.event_name != 'pull_request'
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: production
          work-dir: infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      
      - name: Get Outputs
        if: github.event_name != 'pull_request'
        run: |
          cd infrastructure
          echo "ALB_URL=$(pulumi stack output alb_url)" >> $GITHUB_ENV
          echo "RDS_ENDPOINT=$(pulumi stack output rds_endpoint)" >> $GITHUB_ENV
      
      - name: Output Summary
        if: github.event_name != 'pull_request'
        run: |
          echo "## Deployment Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **ALB URL**: ${{ env.ALB_URL }}" >> $GITHUB_STEP_SUMMARY
          echo "- **RDS Endpoint**: ${{ env.RDS_ENDPOINT }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Access your application at: ${{ env.ALB_URL }}" >> $GITHUB_STEP_SUMMARY
